name: flutter_yoga_workout_4_all_new
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+34

environment:
  sdk: '>=2.19.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  sqflite: ^2.0.3
  #  json_annotation: ^4.4.0
  step_progress_indicator: ^1.0.2
  carousel_slider: ^4.1.1
  numberpicker: ^2.1.1
  flutter_widget_from_html_core: ^0.8.5+3
  country_state_city_picker: ^1.2.8
  palette_generator: ^0.3.3+1
  image_picker: ^0.8.5+3
  flutter_svg: ^1.1.1+1
  percent_indicator: ^4.2.2
  table_calendar: ^3.0.6
  lottie: ^1.4.0
  flutter_share: ^2.0.0
  #  feedback: ^2.4.1
  launch_review: ^3.0.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  flutter_tts: ^3.5.0
  flutter_mailer: ^2.0.1

  intro_slider: ^3.0.9
  wakelock: ^0.6.2
  flutter_local_notifications: ^12.0.2
  http: ^0.13.4
  fluttertoast: ^8.0.9
  scroll_to_index: ^3.0.1
  chewie: ^1.3.3
  #  scroll_to_index: ^2.1.1
  #  admob_flutter: ^2.0.0
#  google_mobile_ads: ^2.0.0

  country_pickers: ^2.0.0

  #  device_info_plus: ^4.0.1
  figma_squircle: ^0.5.3
  path_provider: ^2.0.11
  #  firebase_auth:
  connectivity_plus: ^2.3.6
  rxdart: ^0.27.5
  youtube_player_flutter: ^8.0.0
  timezone: ^0.9.0
  #  flutter_email_sender: ^5.1.0
  pin_input_text_field: ^4.1.2
  #  youtube_player_flutter: ^8.0.0
  audioplayers: ^1.0.1
  #  assets_audio_player: ^3.0.4+1
  html_unescape: ^2.0.0
  flutter_native_timezone: ^2.0.0
  platform_device_id: ^1.0.1
  flutter_keyboard_visibility: ^5.3.0
  in_app_purchase: ^3.1.5
  dio: ^4.0.6
  get: ^4.6.5
  flutter_screenutil: ^5.5.3+2
  hive: ^2.2.3
  shimmer: ^2.0.0
  page_view_dot_indicator: ^2.1.0
  fl_chart: ^0.62.0
  sign_in_with_apple: ^4.3.0
  flutter_facebook_keyhash: ^0.0.4
  flutter_facebook_auth: ^5.0.8
  video_controls: ^1.0.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.4
  flutter_launcher_icons: ^0.13.1
  app_review: ^2.1.2+1
    
  #in_app_purchase_android: ^0.2.5+2

  #firebase_auth: ^4.4.2
  #google_sign_in: ^6.1.0
  #flutter_facebook_auth: ^5.0.8
  #firebase_core: ^2.10.0

flutter_launcher_icons:
  image_path_android: "assets/icons/app-icon-android.png"
  image_path_ios: "assets/icons/app-icon-ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"        
  remove_alpha_ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
#  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/gifs/
    - assets/icons/
  # To add assets to your application, add an assets section, like this:
  #   assets:
  #     - images/a_dot_burr.jpeg
  #     - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-ExtraBold.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf

    - family: Bebasneue
      fonts:
        - asset: fonts/bebasneue_regular.TTF
    - family: MeriendaOne
      fonts:
        - asset: fonts/MeriendaOne-Regular.ttf
    - family: SecularOne
      fonts:
        - asset: fonts/SecularOne-Regular.ttf

    - family: ReemKufi
      fonts:
        - asset: fonts/ReemKufi-Bold.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
